version: '3.8'

services:
  app:
    image: node:22
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: yarn start:dev
    ports:
      - '3000:3000'
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: transaction-authorizer
    ports:
      - '5432:5432'
